/** The calendar grids show a fixed working day rather than only the hours that
 *  happen to hold a session, so an empty week still looks like a schedule. */
export const SCHEDULE_START_HOUR = 7;
export const SCHEDULE_END_HOUR = 22;

function toMinutes(time: string): number {
  const [h, m] = time.split(":").map(Number);
  return h * 60 + m;
}

function toTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

/**
 * Rows for a calendar grid: a fixed 07:00–22:00 axis stepped by the therapist's
 * slot length, unioned with the start time of every session passed in.
 *
 * The union is the important part. Sessions created before the duration changed,
 * or generated by a recurring rule with a different slot length, land on times
 * that the fixed axis would skip — and since cells are looked up by exact
 * "date T time" key, any such session would silently vanish from the calendar.
 * Folding those times in as extra rows keeps every session visible, including
 * ones outside working hours entirely.
 */
export function buildTimeAxis(stepMinutes: number, sessionTimes: Iterable<string>): string[] {
  const times = new Set<string>(sessionTimes);

  // A non-positive step would loop forever; fall back to hourly rows.
  const step = stepMinutes > 0 ? stepMinutes : 60;
  const last = SCHEDULE_END_HOUR * 60;
  for (let minutes = SCHEDULE_START_HOUR * 60; minutes <= last; minutes += step) {
    times.add(toTime(minutes));
  }

  return [...times].sort((a, b) => toMinutes(a) - toMinutes(b));
}
